---
- name: Create users and add to sudo group
  hosts: hr
  become: true
  vars_files:
    - ../vars/hr.yml
  tasks:
    - name: Create users
      loop: "{{ users }}"
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        shell: /bin/bash
        comment: "Ansible managed user"

    - name: Add users to sudo group
      loop: "{{ users }}"
      user:
        name: "{{ item.name }}"
        groups: sudo
        append: yes